export const ADD_MAINCATEGORY = "ADD_MAINCATEGORY";
export const ADD_MAINCATEGORY_RED = "ADD_MAINCATEGORY_RED";
export const GET_MAINCATEGORY = "GET_MAINCATEGORY";
export const GET_MAINCATEGORY_RED = "GET_MAINCATEGORY_RED";
export const UPDATE_MAINCATEGORY = "UPDATE_MAINCATEGORY";
export const UPDATE_MAINCATEGORY_RED = "UPDATE_MAINCATEGORY_RED";
export const DELETE_MAINCATEGORY = "DELETE_MAINCATEGORY";
export const DELETE_MAINCATEGORY_RED = "DELETE_MAINCATEGORY_RED";

export const ADD_SUBCATEGORY = "ADD_SUBCATEGORY";
export const ADD_SUBCATEGORY_RED = "ADD_SUBCATEGORY_RED";
export const GET_SUBCATEGORY = "GET_SUBCATEGORY";
export const GET_SUBCATEGORY_BY_MAIN_ID = "GET_SUBCATEGORY_BY_MAIN_ID";
export const GET_SUBCATEGORY_RED = "GET_SUBCATEGORY_RED";
export const GET_SUBCATEGORY_BY_MAIN_ID_RED = "GET_SUBCATEGORY_BY_MAIN_ID_RED";
export const UPDATE_SUBCATEGORY = "UPDATE_SUBCATEGORY";
export const UPDATE_SUBCATEGORY_RED = "UPDATE_SUBCATEGORY_RED";
export const DELETE_SUBCATEGORY = "DELETE_SUBCATEGORY";
export const DELETE_SUBCATEGORY_RED = "DELETE_SUBCATEGORY_RED";

export const ADD_BRAND = "ADD_BRAND";
export const ADD_BRAND_RED = "ADD_BRAND_RED";
export const GET_BRAND = "GET_BRAND";
export const GET_BRAND_BY_SUB_CATEGORY_ID = "GET_BRAND_BY_SUB_CATEGORY_ID";
export const GET_BRAND_RED = "GET_BRAND_RED";
export const GET_BRAND_BY_SUB_CATEGORY_ID_RED =
  "GET_BRAND_BY_SUB_CATEGORY_ID_RED";
export const UPDATE_BRAND = "UPDATE_BRAND";
export const UPDATE_BRAND_RED = "UPDATE_BRAND_RED";
export const DELETE_BRAND = "DELETE_BRAND";
export const DELETE_BRAND_RED = "DELETE_BRAND_RED";

export const ADD_PRODUCT = "ADD_PRODUCT";
export const ADD_PRODUCT_RED = "ADD_PRODUCT_RED";
export const GET_PRODUCT = "GET_PRODUCT";
export const GET_PRODUCT_RED = "GET_PRODUCT_RED";
export const GET_PRODUCT_BY_MAIN_ID = "GET_PRODUCT_BY_MAIN_ID";
export const GET_PRODUCT_BY_MAIN_ID_RED = "GET_PRODUCT_BY_MAIN_ID_RED";
export const GET_PRODUCT_BY_SUB_ID = "GET_PRODUCT_BY_SUB_ID";
export const GET_PRODUCT_BY_SUB_ID_RED = "GET_PRODUCT_BY_SUB_ID_RED";
export const GET_PRODUCT_BY_BRAND_ID = "GET_PRODUCT_BY_BRAND_ID";
export const GET_PRODUCT_BY_BRAND_ID_RED = "GET_PRODUCT_BY_BRAND_ID_RED";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const UPDATE_PRODUCT_RED = "UPDATE_PRODUCT_RED";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const DELETE_PRODUCT_RED = "DELETE_PRODUCT_RED";

export const ADD_CART = "ADD_CART";
export const ADD_CART_RED = "ADD_CART_RED";
export const GET_CART = "GET_CART";
export const GET_CART_RED = "GET_CART_RED";
export const UPDATE_CART = "UPDATE_CART";
export const UPDATE_CART_RED = "UPDATE_CART_RED";
export const DELETE_CART = "DELETE_CART";
export const DELETE_CART_RED = "DELETE_CART_RED";

export const ADD_WISHLIST = "ADD_WISHLIST";
export const ADD_WISHLIST_RED = "ADD_WISHLIST_RED";
export const GET_WISHLIST = "GET_WISHLIST";
export const GET_WISHLIST_RED = "GET_WISHLIST_RED";
export const DELETE_WISHLIST = "DELETE_WISHLIST";
export const DELETE_WISHLIST_RED = "DELETE_WISHLIST_RED";

export const ADD_CHECKOUT = "ADD_CHECKOUT";
export const ADD_CHECKOUT_RED = "ADD_CHECKOUT_RED";
export const GET_CHECKOUT = "GET_CHECKOUT";
export const GET_CHECKOUT_RED = "GET_CHECKOUT_RED";
export const GET_CHECKOUT_USER = "GET_CHECKOUT_USER";
export const GET_CHECKOUT_USER_RED = "GET_CHECKOUT_USER_RED";
export const UPDATE_CHECKOUT = "UPDATE_CHECKOUT";
export const UPDATE_CHECKOUT_RED = "UPDATE_CHECKOUT_RED";
export const DELETE_CHECKOUT = "DELETE_CHECKOUT";
export const DELETE_CHECKOUT_RED = "DELETE_CHECKOUT_RED";

export const ADD_CONTACT_US = "ADD_CONTACT_US";
export const ADD_CONTACT_US_RED = "ADD_CONTACT_US_RED";
export const GET_CONTACT_US = "GET_CONTACT_US";
export const GET_CONTACT_US_RED = "GET_CONTACT_US_RED";
export const UPDATE_CONTACT_US = "UPDATE_CONTACT_US";
export const UPDATE_CONTACT_US_RED = "UPDATE_CONTACT_US_RED";
export const DELETE_CONTACT_US = "DELETE_CONTACT_US";
export const DELETE_CONTACT_US_RED = "DELETE_CONTACT_US_RED";

export const ADD_NEWSLATTER = "ADD_NEWSLATTER";
export const ADD_NEWSLATTER_RED = "ADD_NEWSLATTER_RED";
export const GET_NEWSLATTER = "GET_NEWSLATTER";
export const GET_NEWSLATTER_RED = "GET_NEWSLATTER_RED";
export const DELETE_NEWSLATTER = "DELETE_NEWSLATTER";
export const DELETE_NEWSLATTER_RED = "DELETE_NEWSLATTER_RED";

export const ADD_VENDOR_CHECKOUT = "ADD_VENDOR_CHECKOUT";
export const DELETE_VENDOR_CHECKOUT = "DELETE_VENDOR_CHECKOUT";
export const GET_VENDOR_CHECKOUT = "GET_VENDOR_CHECKOUT";
export const GET_VENDOR_CHECKOUT_USER = "GET_VENDOR_CHECKOUT_USER";
export const UPDATE_VENDOR_CHECKOUT = "UPDATE_VENDOR_CHECKOUT";
export const DELETE_VENDOR_PRODUCT = "DELETE_VENDOR_PRODUCT";

export const ADD_VENDOR_CHECKOUT_RED = "ADD_VENDOR_CHECKOUT_RED";
export const DELETE_VENDOR_CHECKOUT_RED = "DELETE_VENDOR_CHECKOUT_RED";
export const GET_VENDOR_CHECKOUT_RED = "GET_VENDOR_CHECKOUT_RED";
export const GET_VENDOR_CHECKOUT_USER_RED = "GET_VENDOR_CHECKOUT_USER_RED";
export const UPDATE_VENDOR_CHECKOUT_RED = "UPDATE_VENDOR_CHECKOUT_RED";
export const DELETE_VENDOR_PRODUCT_RED = "DELETE_VENDOR_PRODUCT_RED";

export const ADD_SLUG = "ADD_SLUG";
export const ADD_SLUG_RED = "ADD_SLUG_RED";
export const GET_SLUG = "GET_SLUG";
export const GET_SLUG_RED = "GET_SLUG_RED";
export const UPDATE_SLUG = "UPDATE_SLUG";
export const UPDATE_SLUG_RED = "UPDATE_SLUG_RED";
export const DELETE_SLUG = "DELETE_SLUG";
export const DELETE_SLUG_RED = "DELETE_SLUG_RED";

export const ADD_SUBSLUG = "ADD_SUBSLUG";
export const ADD_SUBSLUG_RED = "ADD_SUBSLUG_RED";
export const GET_SUBSLUG = "GET_SUBSLUG";
export const GET_SUBSLUG_RED = "GET_SUBSLUG_RED";
export const GET_SUBSLUG_BY_PARENT = "GET_SUBSLUG_BY_PARENT";
export const GET_SUBSLUG_BY_PARENT_RED = "GET_SUBSLUG_BY_PARENT_RED";
export const UPDATE_SUBSLUG = "UPDATE_SUBSLUG";
export const UPDATE_SUBSLUG_RED = "UPDATE_SUBSLUG_RED";
export const DELETE_SUBSLUG = "DELETE_SUBSLUG";
export const DELETE_SUBSLUG_RED = "DELETE_SUBSLUG_RED";

// Vendor Slug Constants
export const ADD_VENDOR_SLUG = "ADD_VENDOR_SLUG"
export const ADD_VENDOR_SLUG_RED = "ADD_VENDOR_SLUG_RED"
export const GET_VENDOR_SLUG = "GET_VENDOR_SLUG"
export const GET_VENDOR_SLUG_RED = "GET_VENDOR_SLUG_RED"
export const UPDATE_VENDOR_SLUG = "UPDATE_VENDOR_SLUG"
export const UPDATE_VENDOR_SLUG_RED = "UPDATE_VENDOR_SLUG_RED"
export const DELETE_VENDOR_SLUG = "DELETE_VENDOR_SLUG"
export const DELETE_VENDOR_SLUG_RED = "DELETE_VENDOR_SLUG_RED"

// Vendor Sub Slug Constants
export const ADD_VENDOR_SUBSLUG = "ADD_VENDOR_SUBSLUG"
export const ADD_VENDOR_SUBSLUG_RED = "ADD_VENDOR_SUBSLUG_RED"
export const GET_VENDOR_SUBSLUG = "GET_VENDOR_SUBSLUG"
export const GET_VENDOR_SUBSLUG_RED = "GET_VENDOR_SUBSLUG_RED"
export const GET_VENDOR_SUBSLUG_BY_PARENT = "GET_VENDOR_SUBSLUG_BY_PARENT"
export const GET_VENDOR_SUBSLUG_BY_PARENT_RED = "GET_VENDOR_SUBSLUG_BY_PARENT_RED"
export const UPDATE_VENDOR_SUBSLUG = "UPDATE_VENDOR_SUBSLUG"
export const UPDATE_VENDOR_SUBSLUG_RED = "UPDATE_VENDOR_SUBSLUG_RED"
export const DELETE_VENDOR_SUBSLUG = "DELETE_VENDOR_SUBSLUG"
export const DELETE_VENDOR_SUBSLUG_RED = "DELETE_VENDOR_SUBSLUG_RED"

// Admin Slug Constants
export const ADMIN_ADD_SLUG = "ADMIN_ADD_SLUG"
export const ADMIN_ADD_SLUG_RED = "ADMIN_ADD_SLUG_RED"

export const ADMIN_GET_SLUG = "ADMIN_GET_SLUG"
export const ADMIN_GET_SLUG_RED = "ADMIN_GET_SLUG_RED"

export const ADMIN_UPDATE_SLUG = "ADMIN_UPDATE_SLUG"
export const ADMIN_UPDATE_SLUG_RED = "ADMIN_UPDATE_SLUG_RED"

export const ADMIN_DELETE_SLUG = "ADMIN_DELETE_SLUG"
export const ADMIN_DELETE_SLUG_RED = "ADMIN_DELETE_SLUG_RED"

// Admin Sub-Slug Constants
export const ADMIN_ADD_SUBSLUG = "ADMIN_ADD_SUBSLUG"
export const ADMIN_ADD_SUBSLUG_RED = "ADMIN_ADD_SUBSLUG_RED"

export const ADMIN_GET_SUBSLUG = "ADMIN_GET_SUBSLUG"
export const ADMIN_GET_SUBSLUG_RED = "ADMIN_GET_SUBSLUG_RED"

export const ADMIN_GET_SUBSLUG_BY_PARENT = "ADMIN_GET_SUBSLUG_BY_PARENT"
export const ADMIN_GET_SUBSLUG_BY_PARENT_RED = "ADMIN_GET_SUBSLUG_BY_PARENT_RED"

export const ADMIN_UPDATE_SUBSLUG = "ADMIN_UPDATE_SUBSLUG"
export const ADMIN_UPDATE_SUBSLUG_RED = "ADMIN_UPDATE_SUBSLUG_RED"

export const ADMIN_DELETE_SUBSLUG = "ADMIN_DELETE_SUBSLUG"
export const ADMIN_DELETE_SUBSLUG_RED = "ADMIN_DELETE_SUBSLUG_RED"